apiVersion: apps/v1
kind: Deployment
metadata:
  name: messenger-stable
  labels:
    app: messenger
spec:
  replicas: 3
  selector:
    matchLabels:
      app: messenger
      version: stable
  template:
    metadata:
      labels:
        app: messenger
        version: stable
    spec:
      containers:
      - name: messenger
        image: messenger:stable
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messenger-canary
  labels:
    app: messenger
spec:
    replicas: 1
    selector:
        matchLabels:
          app: messenger
          version: canary
    template:
        metadata:
          labels:
              app: messenger
              version: canary
        spec:
          containers:
          - name: messenger
            image: messenger:canary
            imagePullPolicy: IfNotPresent
            ports:
            - containerPort: 80
              protocol: TCP
          restartPolicy: Always