services:
    auth:
        build: ./services/auth
        ports:
            - "8081:8080"
        depends_on:
            -   postgres
        environment:
            - DB_HOST=postgres
            - DB_USER=user
            - DB_PASSWORD=password
            - DB_NAME=auth_db

    user:
        build: ./services/user
        ports:
            - "8082:8080"
        depends_on:
            -   mongodb
        environment:
            - MONGO_URI=mongodb://mongodb:27017/user_db

    friend:
        build: ./services/friend
        ports:
            - "8083:8080"
        depends_on:
            -   postgres
        environment:
            - DB_HOST=postgres
            - DB_USER=user
            - DB_PASSWORD=password
            - DB_NAME=friend_db

    message:
        build: ./services/message
        ports:
            - "8084:8080"
        depends_on:
            -   scylla
        environment:
            - SCYLLA_HOST=scylla
            - SCYLLA_KEYSPACE=message_keyspace

    postgres:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: auth_db
        volumes:
            -   postgres_data:/var/lib/postgresql/data

    mongodb:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            -   mongodb_data:/data/db

    scylla:
        image: scylladb/scylla:latest
        ports:
            - "9042:9042"
        volumes:
            -   scylla_data:/var/lib/scylla

volumes:
    postgres_data:
    mongodb_data:
    scylla_data: