apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: messenger-monitor
    namespace: default
    labels:
        release: prometheus
spec:
    selector:
        matchLabels:
            app: messenger
    endpoints:
        - port: http
          path: /metrics
          interval: 15s