apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
    name: messenger-alerts
    namespace: default
spec:
    groups:
        - name: messenger
          rules:
              - alert: HighErrorRate
                expr: |
                    sum(rate(http_requests_total{job="messenger",status=~"5.."}[5m]))
                    /
                    sum(rate(http_requests_total{job="messenger"}[5m])) > 0.1
                for: 1m
                labels:
                    severity: critical
                annotations:
                    summary: High error rate detected
                    description: Error rate is above 10% for messenger service
              - alert: HighLatency
                expr: |
                    histogram_quantile(0.95,
                      sum(rate(http_request_duration_seconds_bucket{job="messenger"}[5m])) 
                      by (le)
                    ) > 0.5
                for: 1m
                labels:
                    severity: warning
                annotations:
                    summary: High latency detected
                    description: 95th percentile latency is above 500ms